max-gamma = 150

profile {
    time = 7:30
    # keep identity if you only want to control brightness in the morning
    identity = true
    gamma = 1.0
}

profile {
    time = 21:00
    # strong evening blue-light reduction
    temperature = 3000
    gamma = 0.85
}

# optional deeper night profile
profile {
    time = 23:00
    temperature = 2000
    gamma = 0.7
}

